export const keys = {
  auth: { me: () => ["auth", "me"] as const },
  users: {
    me: () => ["users", "me"] as const,
    detail: (id: string) => ["users", id] as const,
  },
  chauffeurs: {
    me: () => ["chauffeurs", "me"] as const,
    stats: () => ["chauffeurs", "me", "stats"] as const,
    revenus: () => ["chauffeurs", "me", "revenus"] as const,
    vehicules: () => ["chauffeurs", "me", "vehicules"] as const,
    detail: (id: string) => ["chauffeurs", id] as const,
  },
  voyages: {
    all: () => ["voyages"] as const,
    me: () => ["voyages", "me"] as const,
    popular: () => ["voyages", "popular"] as const,
    search: (params: object) => ["voyages", "search", params] as const,
    colisSearch: (params: object) => ["voyages", "colis-search", params] as const,
    detail: (id: string) => ["voyages", id] as const,
    reservations: (id: string, statut?: string) => ["voyages", id, "reservations", statut] as const,
    passagers: (id: string) => ["voyages", id, "passagers"] as const,
  },
  reservations: {
    me: () => ["reservations", "me"] as const,
    incoming: () => ["reservations", "incoming"] as const,
    detail: (id: string) => ["reservations", id] as const,
  },
  colis: {
    me: () => ["colis", "me"] as const,
    byVoyage: (voyageId: string) => ["colis", "voyage", voyageId] as const,
    detail: (id: string) => ["colis", id] as const,
  },
  wallet: {
    me: () => ["wallet", "me"] as const,
    activity: (page: number) => ["wallet", "activity", page] as const,
  },
  transactions: {
    me: (page: number) => ["transactions", "me", page] as const,
    detail: (id: string) => ["transactions", id] as const,
  },
  avis: {
    me: () => ["avis", "me"] as const,
    byChauffeur: (id: string, page: number) => ["avis", "chauffeur", id, page] as const,
  },
  notifications: {
    me: (page: number) => ["notifications", "me", page] as const,
    unreadCount: () => ["notifications", "unread-count"] as const,
  },
  admin: {
    overview: () => ["admin", "overview"] as const,
    kpis: () => ["admin", "kpis"] as const,
    revenus: (period: string) => ["admin", "revenus", period] as const,
    topRoutes: () => ["admin", "top-routes"] as const,
    activity: () => ["admin", "activity"] as const,
    momoStats: () => ["admin", "momo-stats"] as const,
    benefices: (period: string) => ["admin", "benefices", period] as const,
    users: (params?: object) => ["admin", "users", params] as const,
    userDetail: (id: string) => ["admin", "users", id] as const,
    usersStats: () => ["admin", "users", "stats"] as const,
    chauffeurs: (params?: object) => ["admin", "chauffeurs", params] as const,
    chauffeurDetail: (id: string) => ["admin", "chauffeurs", id] as const,
    chauffeurStats: () => ["admin", "chauffeurs", "stats"] as const,
    colis: (params?: object) => ["admin", "colis", params] as const,
    colisDetail: (id: string) => ["admin", "colis", "detail", id] as const,
    pendingColis: () => ["admin", "colis", "pending"] as const,
    inTransitColis: () => ["admin", "colis", "in-transit"] as const,
    kycPending: () => ["admin", "chauffeurs", "kyc-pending"] as const,
    auditLogs: (params?: object) => ["admin", "audit", params] as const,
    auditStats: () => ["admin", "audit", "stats"] as const,
    voyages: (params?: object) => ["admin", "voyages", params] as const,
    voyageDetail: (id: string) => ["admin", "voyages", id] as const,
    voyagesStats: () => ["admin", "voyages", "stats"] as const,
    reservations: (params?: object) => ["admin", "reservations", params] as const,
    reservationDetail: (id: string) => ["admin", "reservations", id] as const,
    reservationsStats: () => ["admin", "reservations", "stats"] as const,
    transactions: (params?: object) => ["admin", "transactions", params] as const,
    transactionsStats: (params?: object) => ["admin", "transactions", "stats", params] as const,
    notifications: (page: number) => ["admin", "notifications", page] as const,
    avis: (params?: object) => ["admin", "avis", params] as const,
    tarifs: () => ["admin", "tarifs"] as const,
    demandes: (params?: object) => ["admin", "demandes", params] as const,
    demandesStats: () => ["admin", "demandes", "stats"] as const,
    userReservations: (userId: string) => ["admin", "users", userId, "reservations"] as const,
    userColis: (userId: string) => ["admin", "users", userId, "colis"] as const,
    userTransactions: (userId: string) => ["admin", "users", userId, "transactions"] as const,
    chauffeurVoyages: (userId: string) => ["admin", "chauffeurs", userId, "voyages"] as const,
    chauffeurRevenus: (userId: string) => ["admin", "chauffeurs", userId, "revenus"] as const,
    payoutAccount: (chauffeurId: string) => ["admin", "chauffeurs", chauffeurId, "payout-account"] as const,
    suggestionVilles: (params?: object) => ["admin", "suggestions-villes", params] as const,
  },
} as const;
